/* Package with an "IMode" interface declaration. */

package traffic_light.IMode


/* allowed traffic light modes */
typedef UInt32 WorkType;
const WorkType WorkRed          = 1;
const WorkType WorkYellow       = 2;
const WorkType WorkGreen        = 4;
const WorkType WorkBlink        = 8;
const WorkType WorkOff          = 16;

const WorkType WorkRedBlink     = 9;
const WorkType WorkYellowBlink  = 10;
const WorkType WorkGreenBlink   = 12;

/* crossways traffic lights */
typedef UInt32 Crossway;
struct CrosswaysMode {
    Crossway dir0;
    Crossway dir1;
}


interface {
    /* IMode interface method */
    SetMode(in CrosswaysMode mode, out CrosswaysMode result);
}
